/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin */

#ifndef _Included_org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin
#define _Included_org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin
 * Method:    nativeSetSurface
 * Signature: (Landroid/view/Surface;II)V
 */
JNIEXPORT void JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_FlutterEngineBridgePlugin_nativeSetSurface
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin
 * Method:    nativeDetachSurface
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_FlutterEngineBridgePlugin_nativeDetachSurface
  (JNIEnv *, jobject);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_FlutterEngineBridgePlugin
 * Method:    nativeSetApplicationContext
 * Signature: (Landroid/content/Context;)V
 */
JNIEXPORT void JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_FlutterEngineBridgePlugin_nativeSetApplicationContext
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
