/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_github_krkr2_flutter_engine_bridge_EngineBindings */

#ifndef _Included_org_github_krkr2_flutter_engine_bridge_EngineBindings
#define _Included_org_github_krkr2_flutter_engine_bridge_EngineBindings
#ifdef __cplusplus
extern "C" {
#endif
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineApiVersion
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineApiVersion 16777216L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultOk
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultOk 0L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultInvalidArgument
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultInvalidArgument -1L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultNotSupported
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineResultNotSupported -3L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateIdle
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateIdle 0L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateRunning
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateRunning 1L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateSucceeded
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateSucceeded 2L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateFailed
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineStartupStateFailed 3L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEnginePixelFormatUnknown
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEnginePixelFormatUnknown 0L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEnginePixelFormatRgba8888
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEnginePixelFormatRgba8888 1L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerDown
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerDown 1L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerMove
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerMove 2L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerUp
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerUp 3L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerScroll
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventPointerScroll 4L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventKeyDown
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventKeyDown 5L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventKeyUp
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventKeyUp 6L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventTextInput
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventTextInput 7L
#undef org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventBack
#define org_github_krkr2_flutter_engine_bridge_EngineBindings_kEngineInputEventBack 8L
/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetRuntimeApiVersion
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetRuntimeApiVersion
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineCreate
 * Signature: (Lorg/github/krkr2/flutter_engine_bridge/EngineCreateDesc;[J)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineCreate
  (JNIEnv *, jobject, jobject, jlongArray);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineOpenGame
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineOpenGame
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineOpenGameAsync
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineOpenGameAsync
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetStartupState
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetStartupState
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineDrainStartupLogs
 * Signature: (J[BI[I)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineDrainStartupLogs
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jintArray);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineTick
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineTick
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    enginePause
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_enginePause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineResume
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineResume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineSetOption
 * Signature: (JLorg/github/krkr2/flutter_engine_bridge/EngineOption;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineSetOption
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineSetSurfaceSize
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineSetSurfaceSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetFrameDesc
 * Signature: (JLorg/github/krkr2/flutter_engine_bridge/EngineFrameDesc;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetFrameDesc
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineReadFrameRgba
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineReadFrameRgba
  (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineSendInput
 * Signature: (JLorg/github/krkr2/flutter_engine_bridge/EngineInputEvent;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineSendInput
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineSetRenderTargetIOSurface
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineSetRenderTargetIOSurface
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineSetRenderTargetSurface
 * Signature: (JLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineSetRenderTargetSurface
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetFrameRenderedFlag
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetFrameRenderedFlag
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetRendererInfo
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetRendererInfo
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetMemoryStats
 * Signature: (JLorg/github/krkr2/flutter_engine_bridge/EngineMemoryStats;)I
 */
JNIEXPORT jint JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetMemoryStats
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_github_krkr2_flutter_engine_bridge_EngineBindings
 * Method:    engineGetLastError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_github_krkr2_flutter_1engine_1bridge_EngineBindings_engineGetLastError
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
